---
swagger: "2.0"
info:
  description: "This is an online bookstore with books, writers and users"
  version: "1.0.0"
  title: "BookStore"
  contact:
    email: "maildiroland@yahoo.it"
  license:
    name: "Apache-2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "hypermedia-app.herokuapp.com"
basePath: "/v2"
tags:
  - name: "book"
    description: "Books availble"
  - name: "event"
    description: "Events of the books"
  - name: "author"
    description: "Writers of the books"
  - name: "user"
    description: "Users subscribed"
  - name: "cart"
    description: "Cart of an user"
schemes:
  - "https"
paths:
  /books:
    get:
      tags:
        - "book"
      summary: "Books availble in the store"
      description: "List of books available in the inventory"
      operationId: "booksGET"
      produces:
        - "application/json"
      parameters: []
      responses:
        200:
          description: "Collection of books"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /books/{id}:
    get:
      tags:
        - "book"
      summary: "Find book with the book's id"
      headers:
        http_headers:
          Access-Control-Allow-Origin: "*"
      operationId: "bookIdGET"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "id of the book you are searching"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "operation was successful"
          schema:
            $ref: "#/definitions/Book"
        400:
          description: "wrong id"
        404:
          description: "Book not found"
      x-swagger-router-controller: "Book"
  /books/{id}/author:
    get:
      tags:
        - "book"
      summary: "Get the author of a book"
      operationId: "booksIdAuthorGET"
      parameters:
        - name: "id"
          in: "path"
          description: "id of the book you want the author of"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Author"
        400:
          description: "Wrong id"
        404:
          description: "Book not found"
      x-swagger-router-controller: "Book"
  /books/{id}/event:
    get:
      tags:
        - "book"
      summary: "Get the event of a book"
      operationId: "booksIdEventGET"
      parameters:
        - name: "id"
          in: "path"
          description: "id of the book you want the event of"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Event"
        400:
          description: "Wrong id"
        404:
          description: "Book not found"
      x-swagger-router-controller: "Book"
  /events:
    get:
      tags:
        - "event"
      summary: "Events related to a book"
      description: "List of all the events"
      operationId: "eventsGET"
      produces:
        - "application/json"
      parameters: []
      responses:
        200:
          description: "Collection of events"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Event"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Event"
  /events/{id}:
    get:
      tags:
        - "event"
      summary: "Find event with the event's id"
      operationId: "eventIdGET"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "id of the event you are searching"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "operation was successful"
          schema:
            $ref: "#/definitions/Event"
        400:
          description: "wrond id"
        404:
          description: "Event not found"
      x-swagger-router-controller: "Event"
  /events/{id}/book:
    get:
      tags:
        - "event"
      summary: "Get the book of an event"
      operationId: "eventsIdBookGET"
      parameters:
        - name: "id"
          in: "path"
          description: "id of the event you want the book of"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Book"
        400:
          description: "Wrong id"
        404:
          description: "Event not found"
      x-swagger-router-controller: "Event"
  /authors:
    get:
      tags:
        - "author"
      summary: "Finds authors"
      description: "Get author"
      operationId: "authorGET"
      produces:
        - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Author"
      x-swagger-router-controller: "Author"
  /authors/{id}:
    get:
      tags:
        - "author"
      summary: "Find authors by ID"
      operationId: "authorIdGET"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "id to get the author"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Author"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Author not found"
      x-swagger-router-controller: "Author"
  /authors/{id}/books:
    get:
      tags:
        - "author"
      summary: "Get the books of an author"
      operationId: "authorsIdBooksGET"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of author of which to get the books"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Author not found"
      x-swagger-router-controller: "Author"
  /user/login:
    post:
      tags:
        - "user"
      summary: "Login"
      description: "Login with a form"
      operationId: "userLoginPOST"
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        - "application/json"
      parameters:
        - name: "email"
          in: "formData"
          required: true
          type: "string"
        - name: "password"
          in: "formData"
          required: true
          type: "string"
      responses:
        200:
          description: "succesfull login"
        404:
          description: "unauthorized"
      x-swagger-router-controller: "User"
  /user/register:
    post:
      tags:
        - "user"
      summary: "Register"
      description: "Register into the store"
      operationId: "userRegisterPOST"
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        - "application/json"
      parameters:
        - name: "email"
          in: "formData"
          required: true
          type: "string"
        - name: "password"
          in: "formData"
          required: true
          type: "string"
      responses:
        200:
          description: "succesfull registration"
        404:
          description: "unauthorized"
      x-swagger-router-controller: "User"
  /users:
    get:
      tags:
        - "user"
      summary: "get all users of the system"
      operationId: "userGET"
      produces:
        - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
      x-swagger-router-controller: "User"
  /users/{id}:
    get:
      tags:
        - "user"
      summary: "Find user with id"
      description: "Returns a single user"
      operationId: "usersIdGET"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "id of user to get"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Invalid ID supplied"
        404:
          description: "User not found"
      x-swagger-router-controller: "User"
  /users/{id}/cart:
    get:
      tags:
        - "user"
      summary: "Get the cart of an user"
      operationId: "usersIdCartGET"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "id of the user to get the cart from"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Cart"
      x-swagger-router-controller: "User"
  /users/logout:
    get:
      tags:
        - "user"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "userLogoutGET"
      produces:
        - "application/xml"
        - "application/json"
      parameters: []
      responses:
        default:
          description: "successful operation"
      x-swagger-router-controller: "User"
  /cart:
    get:
      tags:
        - "cart"
      summary: "Finds a cart"
      description: "Get a cart from the system"
      operationId: "cartGET"
      produces:
        - "application/json"
      parameters:
        - name: "userId"
          in: "query"
          description: "The id of the user of the cart to retrieve"
          required: true
          type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Cart"
        400:
          description: "Invalid userId value"
      x-swagger-router-controller: "Cart"
  /cart/{id}:
    get:
      tags:
        - "cart"
      summary: "Finds a cart by ID"
      operationId: "cartIdGET"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of the cart to get"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Cart"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Cart not found"
      x-swagger-router-controller: "Cart"
    put:
      tags:
        - "cart"
      summary: "Updates a cart in the store with form data"
      operationId: "cartIdPUT"
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of cart that needs to be updated"
          required: true
          type: "integer"
          format: "int64"
        - name: "books"
          in: "formData"
          description: "Updated array of books in the cart"
          required: true
          type: "array"
          items:
            type: "integer"
            format: "int64"
          collectionFormat: "multi"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Cart"
definitions:
  Book:
    type: "object"
    required:
      - "id"
      - "price"
      - "title"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      price:
        type: "number"
        format: "double"
      isbn:
        type: "string"
      genre:
        type: "string"
      quantity:
        type: "integer"
        format: "int32"
      description:
        type: "string"
      publisher:
        type: "string"
      language:
        type: "string"
      release:
        type: "string"
        format: "date"
    title: "Book"
    xml:
      name: "Book"
    description: "A book for sale in the store"
    example:
      id: 0
      title: "Harry Potter 1"
      price: 10
      isbn: "9780747532743"
      genre: "fantasy"
      quantity: 3
      publisher: "Bloomsbury Publishing"
      language: "english"
      release: "1997-06-26"
  Event:
    type: "object"
    required:
      - "bookId"
      - "date"
      - "id"
      - "location"
      - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      bookId:
        type: "integer"
        format: "int64"
      date:
        type: "string"
        format: "date"
      location:
        type: "string"
      descritpion:
        type: "string"
    title: "Event"
    xml:
      name: "Event"
    description: "An event related to a book"
    example:
      id: 0
      name: "Harry Potter reunion"
      date: "2017-07-21"
      location: "London"
      description: "All together to make magic"
  Author:
    type: "object"
    required:
      - "id"
      - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      surname:
        type: "string"
      biography:
        type: "string"
    xml:
      name: "Author"
    description: "Book writer"
    example:
      id: 5
      name: "Joanne"
      surname: "Rowling"
      biography: "Author of the famous Harry Potter books"
  User:
    type: "object"
    required:
      - "email"
      - "password"
    properties:
      email:
        type: "string"
      password:
        type: "string"
    xml:
      name: "User"
    example:
      email: "harry.potter@gmail.com"
      password: "wingardiumleviosa"

  Cart:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      userId:
        type: "string"
    example:
      id: 0
      userId: 0
